### ISSUE TITLE
[QUESTION] is the "feed" api working?

### ISSUE THREAD

**Issue by fcastillao** [vooolll/facebook4s#164]
im trying to use the feed api as in the examples:

`  facebookClient.feed(FacebookUserId(userId.value)) map(feed =>
    println(feed))
`

but trying to do that way gives me an error:

```
java.lang.RuntimeException: Attempt to decode value on failed cursor: DownField(id),DownField(target),DownArray,DownField(data),DownField(attachments),MoveRight,DownArray,DownField(data)
	at com.github.vooolll.services.DomainParsing$$anonfun$parse$1.applyOrElse(DomainParsing.scala:74)
	at com.github.vooolll.services.DomainParsing$$anonfun$parse$1.applyOrElse(DomainParsing.scala:73)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recover(Try.scala:230)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:391)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

am i doing something wrong?

**Comment by vooolll** [comment]
Could you provide json you expecting ? Looks like library cant decode it.

**Comment by vooolll** [comment]
@fcastillao Looks like library can't parse attachments, as it expects something that is not there, I could fix it quickly if you provide json that is returned by endpoint, you could check it using Graph Api Explorer - https://developers.facebook.com/tools/explorer/

**Comment by vooolll** [comment]
You could also try to exclude `FacebookPostAttributes.Attachments` according to signature : 
`def feed(userId: UserId, fields: Set[_ <: PostAttribute])`  . 

So if you need quick work around you could do something like this:

`import com.github.vooolll.domain.posts.FacebookPostAttributes._`

`facebookClient.feed(FacebookUserId(userId.value), Set(Id, Messages, CreatedTime, ObjectId, Picture, From, Name))`

**Comment by fcastillao** [comment]
post with attachments should appear in the graph explorer "/feed" endpoint? because i only see post with "message" "created_time" and "id"

so, the issue is with multiline messages? so i guess is messages like these ones?:

```
    {
      "message": "#EntryNumber17

https://www.youtube.com/watch?v=scp-03pNOvI

artista: https://iiiostiii.tumblr.com/post/173923239869/undertale",
      "created_time": "2018-11-27T16:45:48+0000",
      "id": "10156795923942486_10156786085697486"
    },
```

```
    {
      "message": "#FraseDelDia:

\"No es un bug, es un feature\"",
      "created_time": "2018-11-26T20:11:30+0000",
      "id": "10156795923942486_10156784113282486"
    }
```

**Comment by vooolll** [comment]
@fcastillao I don't think that problem is in 2 line messages, as facebook service can't return invalid json. Could you please add `?fields=attachments` query to your feed request

**Comment by vooolll** [comment]
@fcastillao have you tried to disable attachment by not passing it?

**Comment by fcastillao** [comment]
cutted out sample of attaching the `?fields=attachments` to the /xxxxxx/feed query

```
{
  "data": [
    {
      "id": "10156795923942486_10156799159382486",
      "attachments": {
        "data": [
          {
            "media": {
              "image": {
                "height": 720,
                "src": "https://scontent.xx.fbcdn.net/v/t1.0-9/s720x720/47301783_357047315029628_2419956729740525568_n.jpg?_nc_cat=104&_nc_ht=scontent.xx&oh=497eda1bfb80d1c5064e5049ea8fa79b&oe=5C69EACC",
                "width": 405
              }
            },
            "target": {
              "id": "357047311696295",
              "url": "https://www.facebook.com/zucculentmeme/photos/a.245070309560663/357047311696295/?type=3"
            },
            "type": "photo",
            "url": "https://www.facebook.com/zucculentmeme/photos/a.245070309560663/357047311696295/?type=3"
          }
        ]
      }
    },
    {
      "id": "10156795923942486_10156798927882486",
      "attachments": {
        "data": [
          {
            "media": {
              "image": {
                "height": 360,
                "src": "https://scontent.xx.fbcdn.net/v/t15.5256-10/46185415_364863630938726_8778553788815376384_n.jpg?_nc_cat=1&_nc_ht=scontent.xx&oh=cb7d98d2c04b6045166c21862da8de1a&oe=5CACA2D3",
                "width": 640
              }
            },
            "target": {
              "id": "364863364272086",
              "url": "https://www.facebook.com/Neritodejeelvisaje/videos/364863364272086/"
            },
            "type": "video_autoplay",
            "url": "https://www.facebook.com/Neritodejeelvisaje/videos/364863364272086/"
          }
        ]
      }
    },
    {
      "id": "10156795923942486_10156798150007486",
      "attachments": {
        "data": [
          {
            "media": {
              "image": {
                "height": 720,
                "src": "https://scontent.xx.fbcdn.net/v/t15.5256-10/s720x720/46209108_333339157495574_2020225429171863552_n.jpg?_nc_cat=106&_nc_ht=scontent.xx&oh=091b871540d3de3994e38f5ea998792e&oe=5CAF86EE",
                "width": 490
              }
            },
            "target": {
              "id": "333334647496025",
              "url": "https://www.facebook.com/ojocolombianooficial/videos/333334647496025/"
            },
            "type": "video_autoplay",
            "url": "https://www.facebook.com/ojocolombianooficial/videos/333334647496025/"
          }
        ]
      }
    },
    {
      "id": "10156795923942486_10156797796487486",
      "attachments": {
        "data": [
          {
            "subattachments": {
              "data": [
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/47032389_2570693102957313_7509859898851590144_n.jpg?_nc_cat=104&_nc_ht=scontent.xx&oh=25a6870b9c20f878627b5578c728ec5e&oe=5C6389B6",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693096290647",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693096290647/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693096290647/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/47181250_2570693116290645_6432015427601170432_n.jpg?_nc_cat=106&_nc_ht=scontent.xx&oh=047a0c1a2c45d000cd2469e1e142c9c5&oe=5C6864F2",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693112957312",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693112957312/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693112957312/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46972514_2570693129623977_2633350071013343232_n.jpg?_nc_cat=110&_nc_ht=scontent.xx&oh=8dbef3f0eaebf94ab498b7c9d8f9617a&oe=5CB18B6F",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693126290644",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693126290644/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693126290644/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46811008_2570693149623975_4612189702127091712_n.jpg?_nc_cat=108&_nc_ht=scontent.xx&oh=eb45cff37bc0c0457a5520fa6930bd27&oe=5C70DF24",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693146290642",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693146290642/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693146290642/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46897235_2570693169623973_5226616075541544960_n.jpg?_nc_cat=107&_nc_ht=scontent.xx&oh=58d4aa4952ed24c36dca518cee7db483&oe=5CABEA94",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693166290640",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693166290640/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693166290640/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46893562_2570693192957304_9103658993233952768_n.jpg?_nc_cat=102&_nc_ht=scontent.xx&oh=0f197b7ddc5294cda06534ccffa41bd5&oe=5C676141",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693189623971",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693189623971/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693189623971/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/47062135_2570693202957303_695065136016130048_n.jpg?_nc_cat=111&_nc_ht=scontent.xx&oh=5f9f3f11818a825744045f815bc75bb9&oe=5CA36DE2",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693199623970",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693199623970/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693199623970/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/47115810_2570693239623966_2400423987277463552_n.jpg?_nc_cat=100&_nc_ht=scontent.xx&oh=ed0f2e2d5eb0be23c56fbd31dd777bfc&oe=5CB26B30",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693236290633",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693236290633/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693236290633/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46820748_2570693249623965_3040552772136075264_n.jpg?_nc_cat=103&_nc_ht=scontent.xx&oh=6381df2aa4f4c2368c117f05ae1e562d&oe=5C68D8C7",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693246290632",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693246290632/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693246290632/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46753129_2570693272957296_5458687215972384768_n.jpg?_nc_cat=107&_nc_ht=scontent.xx&oh=611cb593c7b2b4eca793257c011b11d3&oe=5CA0C176",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693269623963",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693269623963/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693269623963/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46939146_2570693279623962_6639903565693321216_n.jpg?_nc_cat=111&_nc_ht=scontent.xx&oh=8dc4f528ca83d627ca41e5515429e008&oe=5C6D68B3",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693276290629",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693276290629/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693276290629/?type=3"
                },
                {
                  "media": {
                    "image": {
                      "height": 720,
                      "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p480x480/46819818_2570693332957290_8535201633313751040_n.jpg?_nc_cat=108&_nc_ht=scontent.xx&oh=860fe66834c022e3dbbf65bad9561a33&oe=5CA5A200",
                      "width": 480
                    }
                  },
                  "target": {
                    "id": "2570693329623957",
                    "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693329623957/?type=3"
                  },
                  "type": "photo",
                  "url": "https://www.facebook.com/electric.luxray/photos/a.826607904032517/2570693329623957/?type=3"
                }
              ]
            },
            "target": {
              "id": "2570693696290587",
              "url": "https://www.facebook.com/825244684168839/posts/2570693696290587/"
            },
            "title": "Photos from Luxray's post",
            "type": "album",
            "url": "https://www.facebook.com/825244684168839/posts/2570693696290587/"
          }
        ]
      }
    },
```

**Comment by fcastillao** [comment]
not tried disabling attachments in my code since im at work ahaha

**Comment by vooolll** [comment]
:D looks like not full json, does it have `paging`? . If I add `paging` it is passing test. 

I call:
`/xxx/feed?fields=attachments,object_id,created_time,picture,from,name,message,id`

and basically parse response to: 

`final case class FacebookFeed(posts: List[FacebookPost], paging: FacebookFeedPaging)`

**Comment by fcastillao** [comment]
yes it has paging at the bottom:

```
    {
      "id": "10156795923942486_10156788931177486",
      "attachments": {
        "data": [
          {
            "media": {
              "image": {
                "height": 540,
                "src": "https://scontent.xx.fbcdn.net/v/t1.0-0/p180x540/46973005_10156788931117486_3711312409051267072_o.jpg?_nc_cat=111&_nc_ht=scontent.xx&oh=c005c20d3d02c281f625490afc83ee92&oe=5C655EBB",
                "width": 720
              }
            },
            "target": {
              "id": "10156788931112486",
              "url": "https://www.facebook.com/photo.php?fbid=10156788931112486&set=p.10156788931112486&type=3"
            },
            "type": "photo",
            "url": "https://www.facebook.com/photo.php?fbid=10156788931112486&set=p.10156788931112486&type=3"
          }
        ]
      }
    }
  ],
  "paging": {
    "previous": "https://graph.facebook.com/v3.2/10156795923942486/feed?fields=attachments&format=json&since=1543848780&access_token=EAAbkXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXb674oHREj8ZBijqDogs&__previous=1",
    "next": "https://graph.facebook.com/v3.2/10156795923942486/feed?fields=attachments&format=json&access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&limit=25&until=1543450013&__paging_token=enc_AdAaeXUpXXXXXXXXXXXXXXXXXXXXXXXXKwKZAPAEoKKShGX5Jb4rLc5EK7ej7DrIXm4UQZCacfmdognxAVb4B"
  }
}
```

**Comment by vooolll** [comment]
@fcastillao I reproduced it by pasting my own feed. Will fix it :D

**Comment by fcastillao** [comment]
great! :D if there is anything i can help with dont hesitate

tnx @vooolll

**Comment by vooolll** [comment]
@fcastillao you could use `0.3.3` it should work. Thanks for your contribution.

**Comment by vooolll** [comment]
@fcastillao so have you managed to get a feed?

**Comment by fcastillao** [comment]
oh yes, sorry for not replying haha.

as soon as you updated to 0.3.3 it worked :) thanks a ton @vooolll
