### ISSUE TITLE
Wrong value FacebookClientId - should be 15 not 16

### ISSUE THREAD

**Issue by miggi** [vooolll/facebook4s#53]
Hey, your app is not usable. FacebookClientId is = 15, not 16 - not working for my AppID (newly created)
```
Caused by: java.lang.IllegalArgumentException: requirement failed: Wrong facebook app id (client id) length
	at scala.Predef$.require(Predef.scala:277)
	at domain.oauth.FixedSizeValue.<init>(FacebookAccessToken.scala:20)
```

**Comment by vooolll** [comment]
@miggi Hi, you are right. I will fix it ASAP

**Comment by vooolll** [comment]
@miggi you just need to install `0.2.1`

**Comment by miggi** [comment]
@vooolll thanks :)
